framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'  
    trusted_hosts: '%env(TRUSTED_HOSTS)%'     
     
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto    
        cookie_samesite: lax       
        storage_factory_id: session.storage.factory.native

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file