services:
  - type: web
    name: task4-app
    env: docker
    repo: https://github.com/TheMordo26/task_4_GEPP
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: task4-db
          property: connectionString

databases:
  - name: task4-db
    plan: free
    databaseName: task4
    user: task4user