services:
  - type: web
    name: task4-app
    env: php
    plan: free
    repo: https://github.com/TheMordo26/task_4_GEPP
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: task4-db
          property: connectionString

databases:
  - name: task4-db
    plan: free
    databaseName: task4
    user: task4user